version: '3.7'
name: geoclient

services:
  webserver:
    image: wrkfmdit/geoclient:${GEOCLIENT_TAG:-latest}
    volumes:
      - type: bind
        source: ${MLS_GEOCLIENT_CONFIG:-./config}
        target: /app/config/
        read_only: true
    ports:
      - "8070:80"

  geobroker:
    image: wrkfmdit/geobroker:${GEOBROKER_TAG:-latest}
    # Add for debugging purposes only
    #ports:
    #  - "8071:8080"

networks:
  default:
    name: mls-network
