name: Build Geoclient Docker image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: wrk-fmd/mls-packages/.github/workflows/docker-build.yml@main
    with:
      DOCKER_CONTEXT: ./docker
      DOCKER_NAME: wrkfmdit/geoclient
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
